/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Santiago
 * Created: 11 ago. 2020




    CREAR BASE DE DATOS LLAMADA RegistroMedico
    USERNAME: root
    PASSWORD: root


 */


CREATE TABLE ATLETA ( 
CODIGO_ATLETA INT 
PRIMARY KEY NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1,INCREMENT BY 1), 
CEDULA_A INT NOT NULL,
NOMBRE_A VARCHAR (25) NOT NULL, 
APELLIDO_A VARCHAR (25) NOT NULL, 
FECHA_NACI_A DATE NOT NULL,
PESO_A double NOT NULL,
CORREO_A VARCHAR (50) NOT NULL,
DIRECCION_A VARCHAR (100) NOT NULL,
TELEFONO_A INT NOT NULL);


CREATE TABLE MEDICO ( 
CODIGO_MEDICO INT 
PRIMARY KEY NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1,INCREMENT BY 1), 
CEDULA_M INT NOT NULL,
NOMBRE_M VARCHAR (25) NOT NULL, 
APELLIDO_M VARCHAR (25) NOT NULL, 
FECHA_NACI_M DATE NOT NULL,
CORREO_M VARCHAR (50) NOT NULL,
DIRECCION_M VARCHAR (100) NOT NULL, 
TELEFONO_M INT NOT NULL,
SALARIO_M double NOT NULL,
ESPECIALIDAD_M VARCHAR (25) NOT NULL);


CREATE TABLE CONSULTA ( 
CODIGO_CONSULTA INT 
PRIMARY KEY NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1,INCREMENT BY 1), 
ALERGIA_C VARCHAR (80),
SINTOMA_C VARCHAR (80) NOT NULL, 
PADECIMIENTO_C VARCHAR (80) ,
OBSERVACION_C VARCHAR (150) ,
FECHA_C DATE NOT NULL,
CODIGO_ATLETA INT NOT NULL,
CODIGO_MEDICO INT  NOT NULL,
CODIGO_RECETA INT  NOT NULL);


CREATE TABLE RECETA ( 
CODIGO_RECETA INT 
PRIMARY KEY 
NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1,INCREMENT BY 1), 
DOSIS_R VARCHAR (30) NOT NULL, 
DESCRIPCION_R VARCHAR (150),
CANTIDAD_R INT NOT NULL,
FECHA_R DATE NOT NULL);




CREATE TABLE MEDICAMENTO ( 
CODIGO_MEDICAMENTO INT 
PRIMARY KEY NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1,INCREMENT BY 1),
NOMBRE_MD VARCHAR (30) NOT NULL, 
DESCRIPCION_MD VARCHAR (150) NOT NULL, 
CANTIDAD_MD INT NOT NULL);


CREATE TABLE PROVEEDOR ( 
CODIGO_PROVEEDOR INT 
PRIMARY KEY NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1,INCREMENT BY 1), 
NOMBRE_P VARCHAR (50) NOT NULL, 
DIRECCION_P VARCHAR (100)  NOT NULL, 
PROVINCIA_P VARCHAR (20) NOT NULL,
TELEFONO_P INT NOT NULL,
CORREO_P VARCHAR (50) NOT NULL); 





CREATE TABLE PROVEEDOR_MEDICAMENTO ( 
	CODIGO_MEDICAMENTO INT NOT NULL,
	CODIGO_PROVEEDOR INT NOT NULL,
	PRIMARY KEY (CODIGO_MEDICAMENTO,CODIGO_PROVEEDOR),
	FOREIGN KEY (CODIGO_MEDICAMENTO) REFERENCES MEDICAMENTO(CODIGO_MEDICAMENTO),
	FOREIGN KEY (CODIGO_PROVEEDOR) REFERENCES PROVEEDOR(CODIGO_PROVEEDOR));


CREATE TABLE MEDICAMENTO_RECETA ( 
	CODIGO_MEDICAMENTO INT NOT NULL,
	CODIGO_RECETA INT NOT NULL,
	PRIMARY KEY (CODIGO_MEDICAMENTO,CODIGO_RECETA),
	FOREIGN KEY (CODIGO_MEDICAMENTO) REFERENCES MEDICAMENTO(CODIGO_MEDICAMENTO),
	FOREIGN KEY (CODIGO_RECETA) REFERENCES RECETA(CODIGO_RECETA));



CREATE TABLE ROL (
ID_ROL INT NOT NULL primary key,
  DESCRIPCION_ROL VARCHAR(30) NOT NULL,
  PLANTILLA_ROL VARCHAR(15) NOT NULL
);

insert into rol values(1,'privilegios de usuario','usuario');
insert into rol values(2,'privilegios de administrador','administrador');
insert into rol values(3,'privilegios de Respaldo','respaldo');


CREATE TABLE USUARIO ( 
ID_USUARIO varchar(90) primary key , 
ROL INT NOT NULL, 
NOMBRE_U VARCHAR (25) NOT NULL, 
APELLIDO_U VARCHAR (25) NOT NULL, 
CORREO_U VARCHAR (80) NOT NULL,
PASSWORD_1 VARCHAR (20) not null,
PASSWORD_2 VARCHAR (20) ,
ACTIVO boolean default true,
 FOREIGN KEY (ROL) REFERENCES ROL(ID_ROL)

);

INSERT INTO USUARIO (Id_usuario,ROL,NOMBRE_U,APELLIDO_U,CORREO_U,PASSWORD_1,PASSWORD_2,ACTIVO)
VALUES('eduardo',1,'Eduardo','Farulla','efarulla@hotmail.com','eduardo','eduardo',true),
      ('santiago',2,'Castillo','Picado','santicastillop@gmail.com','santiago','santiago',true),
      ('orlando',3,'ugalde','Guzman','efarulla@hotmail.com','orlando','orlando',true);





ALTER TABLE CONSULTA 
ADD CONSTRAINT FK_CODIGO_ATLETA 
FOREIGN KEY (CODIGO_ATLETA) REFERENCES ATLETA(CODIGO_ATLETA);

ALTER TABLE CONSULTA 
ADD CONSTRAINT FK_CODIGO_MEDICO
FOREIGN KEY (CODIGO_MEDICO) REFERENCES MEDICO(CODIGO_MEDICO);

ALTER TABLE CONSULTA 
ADD CONSTRAINT FK_CODIGO_RECETA 
FOREIGN KEY (CODIGO_RECETA) REFERENCES RECETA(CODIGO_RECETA);


ALTER TABLE EXPEDIENTE 
ADD CONSTRAINT FK_CODIGO_CONSULTA
FOREIGN KEY (CODIGO_CONSULTA) REFERENCES CONSULTA(CODIGO_CONSULTA);



--ALTER TABLE PROVEEDOR ALTER COLUMN TELEFONO_P INT NOT NULL;

--INSERTAR DATOS EN TABLAS--
 

INSERT INTO ATLETA (CEDULA_A,NOMBRE_A,APELLIDO_A,FECHA_NACI_A,PESO_A,CORREO_A,DIRECCION_A,TELEFONO_A) 
VALUES (302930283,'SERGIO','BRENES MORA','1990-03-01',70.20,'SERG@GMAIL.COM','CARTAGO, PARAISO',87889656),
    (302980283,'MARCO','MORA CASTILLO','1992-03-09',65.98,'MAR@GMAIL.COM','SAN JOSE, CURRIDABAT',87899656),
    (302830500,'FELIPE','VARELA MORA','1993-05-08',62.87,'FEL@GMAIL.COM','CARTAGO',89889656),
    (102930283,'MARIO','MENDEZ MORA','1995-06-05',69.25,'MAR@GMAIL.COM','ALAJUELA',88552200),
    (702930983,'ALVIN','BRENES MATA','1990-03-09',72.23,'ALV@GMAIL.COM','PUNTARENAS',71025522),
    (106930283,'THIAGO','MATA MORA','1991-10-01',63.27,'THI@GMAIL.COM','CARTAGO, TEJAR',71526365),
    (302930283,'CARLOS','CASTILLO MORA','1996-11-03',60.60,'CAR@GMAIL.COM','CARTAGO, GUARCO',71254563),
    (602930283,'RAFAEL','CHAVEZ ALFARO','1997-12-01',60.89,'RAF@GMAIL.COM','SAN JOSE, SAN PEDRO',70452585);



INSERT INTO MEDICO (CEDULA_M,NOMBRE_M,APELLIDO_M,FECHA_NACI_M,CORREO_M,DIRECCION_M,TELEFONO_M,SALARIO_M,ESPECIALIDAD_M)
VALUES (602950398,'DAVID','COTO MORALES','1985-05-09','DAV@GMAIL.COM','CARTAGO, PARAISO',87889956,2000000,'MEDICO GENERAL');


INSERT INTO MEDICAMENTO (NOMBRE_MD,DESCRIPCION_MD,CANTIDAD_MD)
VALUES  ('PARACETAMOL','ANALGESICO',1000),
        ('IBUPROFENO','DESINFLAMANTE',1000),
        ('ACETAMINIFEN','ANALGESICO',1000);


INSERT INTO PROVEEDOR (NOMBRE_P,DIRECCION_P,PROVINCIA_P,TELEFONO_P,CORREO_P)
VALUES ('STEIN','CARTAGO','CARTAGO',25522698,'MEDICAMENTOS@STEIN.COM'),
       ('GUTIS','SEAMPARADOS','SAN JOSE',25663388,'GUTISFARMACOS@HOTMAIL.COM');


INSERT INTO RECETA (DOSIS_R,DESCRIPCION_R,CANTIDAD_R,FECHA_R)
VALUES ('2 VECES AL DIA CADA 12 HORAS','TOMAR CON AGUA EN EL HORARIO INDICADO',20,'2020-03-29');



INSERT INTO PROVEEDOR_MEDICAMENTO VALUES (1,1);


INSERT INTO MEDICAMENTO_RECETA VALUES(1,1);


INSERT INTO CONSULTA (ALERGIA_C,SINTOMA_C,PADECIMIENTO_C,OBSERVACION_C,FECHA_C,CODIGO_ATLETA,CODIGO_MEDICO,CODIGO_RECETA)
VALUES('NO TIENE ALERGIAS','DOLOR DE ANTEBRAZO DERECHO','ROTURA DEL TENDON','REPOSAR POR 2 SEMANAS','2020-04-20',1,1,1);


